var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                               xxx           ",
   "  x       xxxxxxxxx                                xx      xx    xx!xx          ",
   "  x   x                       x              xx                  x!!!x          ",
   "  x                   xxxx                                       xx!xx          ",
   "  xx                              xxxxxx                          xvx           ",
   "    xxx                           x                                         xx  ",
   "  xx   xxx                        x                                          x  ",
   "  x                               x                                          x  ",
   "  x                               x      xxxxx                               x  ",
   "  x          xxxx                 x                                          x  ",
   "  x  @       x  x                 x                              xxxxx     o x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxPx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                xx                                                                                           x!x  ",
   "                 x                              xxxx                                                         x!x  ",
   "                 x          x                   x!!x                                                         x!x  ",
   "                 x                x    xxxxxxxxxx!!x                               oo                       xx!x  ",
   "                 x                               x!x                               xx         xxxxxxxxxxxxxxx!!x  ",
   "                xx   x                           xvxxx             x   x                        !!!!!!!!!!!!!!xx  ",
   "                 x                                   x       xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                 x          x                        x        xx!!!!!!!!!!!xx            v                        ",
   "                 x               xx                  x         xxxx!!!!!xxxx                                      ",
   "                 x!!!!!!!!!!!!!!!xxxxxxxxxxxxxxx     x            xxxxxxx        xxx         xxx                  ",
   "                xxxxxxxxxxxxxxxxx              x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                     C         x     x               x   x         x         x                    ",
   "                               xx   xxx        x     x               x   x         x         x                    ",
   "              xxxxxxxxx         x   x!!!!!!!!!!x     x     xxxxxx    x   x!!!xxxxxxxxx       x                    ",
   "             xx       xx        x   x!!!!!!!!!!x    xx               x   x!!!x               x                    ",
   "     @       x         x        x   x!!!!!!!!!!x     x               x   x!!!x               x                    ",
   "    xxx      x         x        x   x!!!!!!!!!!x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx   xx!!!!!!!!!x     x               x           x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx        xxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx       xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    x                 xx!!!!!!xx !                    xx  C  xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx!!!!!!xxxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["    x                                                                                                         ",
   "                     xxx                                                                                      ",
   "                     x                                                                                        ",
   "                     x                                                                                        ",
   "                     x      xxxxxxxxxxxxxxxxxxxxxxx                                                 xxx       ",
   "                     x      x                     x                                                   x       ",
   "                    xxxx    x        xx           x                                                   x       ",
   "       x     x       x      x        Px           x                                                   x       ",
   "       x!!!!!x       x      x                     x           xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxxxxxx       ",
   "       x!!!!!x       x      x  xx                 x                                                           ",
   "       x!!!!!x       xxxxxxxx               x     x                                                   x       ",
   "       x!!!!!x                                    x                                                   x       ",
   "       !!!!!!!                      xxx          xx          xxxx       xxxxx       xxxxxxxx    xxxxxxx       ",
   "       vvvvvvv                         xx         x                                                           ",
   "                                                  x       xx                                                  ",
   "                                                 xx                                                           ",
   "                                         x x      x                                                           ",
   "                                       x          xxxxxx                                                      ",
   "        x          xxx         xxx                x  v                                                        ",
   "                                                  x                                                           ",
   "                                                  x    v                        x      x                      ",
   "                                                  x       xxxxxxxxx                                           ",
   "             xxx         xxx         xxx          x                      x                  x                 ",
   "   C                                              x                                                           ",
   "   xxxxxxxxx                                      x              ||                                           ",
   "  x         x                                     x                                                           ",
   "  x         x   xxxxxxxxx   xxxxxxxxx   xx        x                                       x                   ",
   "  x         x   x       x   x       x   x         x                      o    x     x                         ",
   "  x  @      xxxxx       xxxxx       xxxxx         x                                                           ",
   "  xxxxxxx                                     xxxxx      xxx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
   ["                                                                                                             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ", 
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                          v v v v v v v v v v v v v v v v v v v v v v v v v                                   ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                               !                                              ",
   "                                     x  x    x   x  x  x   x   !                                              ",
   "                                     x  x    x   x  x  xx  x   !                                              ",
   "                                     x  x    x x x  x  x x x   !                                              ",
   "                                     xxxx     x x   x  x  xx                                                  ",
   "                                                               !                                              ",
   "                                                                                                              ",
   "                                                  @                                                           ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
