var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                               xxx           ",
   "  x       xxxxxxxxx                                xx      xx    xx!xx          ",
   "  x   x                       x              xx                  x!!!x          ",
   "  x                   xxxx                                       xx!xx          ",
   "  xx                              xxxxxx                          xvx           ",
   "    xxx                           x                                         xx  ",
   "  xx   xxx                        x                                          x  ",
   "  x                               x                                          x  ",
   "  x                               x      xxxxx                               x  ",
   "  x          xxxx                 x                                          x  ",
   "  x  @       x  x            P    x                              xxxxx     o x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                 x                                                                                           x!x  ",
   "                 x                                                                                           x!x  ",
   "                 x                                                                                           x!x  ",
   "                 x                              xxxx                                                         x!x  ",
   "                 x          x                   x!!x                                                         x!x  ",
   "                 x                x    xxxxxxxxxx!!x                               oo                       xx!x  ",
   "                 x                               x!x                               xx         xxxxxxxxxxxxxxx!!x  ",
   "                 x   x                           xvxxx             x   x                        !!!!!!!!!!!!!!xx  ",
   "                 x                                   x       xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                 x          x                        x        xx!!!!!!!!!!!xx            v                        ",
   "                 x               xx                  x         xxxx!!!!!xxxx                                      ",
   "                 x!!!!!!!!!!!!!!!xxxxxxxxxxxxxxx     x            xxxxxxx        xxx         xxx                  ",
   "                 xxxxxxxxxxxxxxxx              x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x    x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x               x   x         x         x                    ",
   "                              xxx   xxx        x     x               x   x         x         x                    ",
   "              xxxxxxxxx         x   x          x     x     xxxxxx    x   x!!!xxxxxxxxx       x                    ",
   "             xx       xx        x   x          x    xx               x   x!!!x               x                    ",
   "     @       x         x        x   x          x     x               x   x!!!x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx   xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx       xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    x                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx!!!!!!!xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                    xxx       ",
   "                                                                                                    xox       ",
   "                                                                                                    x x       ",
   "                   xxx                                                                                x       ",
   "       !!!!!!!      v                                         xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxxxxxx       ",
   "       x!!!!!x                                                                                                ",
   "       x!!!!!x            x                                                                           x       ",
   "       x!!!!!x                          xx                                                            x       ",
   "       !!!!!!!                          v                    xxxx       xxxxx       xxxxxxxx    xxxxxxx       ",
   "       vvvvvvv                                                                                                ",
   "                         xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                  xxxxxx                                                      ",
   "                   xxx         xxx                x  v                                                        ",
   "                                                  x                                                           ",
   "                                                  x    v                        x      x                      ",
   "                                                  x       xxxxxxxxx                                           ",
   "             xxx         xxx         xxx          x                      x                  x                 ",
   "                                                  x                                                           ",
   "                                                  x              ||                                           ",
   "  xxxxxxxxxxx                                     x                                                           ",
   "  x         x   xxxxxxxxx   xxxxxxxxx   xx        x                                       x                   ",
   "  x         x P x       x P x       x P x         x                           x     x                         ",
   "  x  @      xxxxx       xxxxx       xxxxx         x                                                           ",
   "  xxxxxxx                                     xxxxx      xxx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
   ["                                                                                                             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ", 
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                        @                                                     ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
